module(
    name = "silence_operator",
    version = "0.0.0",
)

bazel_dep(name = "rules_go", version = "0.63.0")
bazel_dep(name = "gazelle", version = "0.53.0")
bazel_dep(name = "package_metadata", version = "0.0.13")

addlicense_repo = use_repo_rule("//bazel:addlicense_toolchain.bzl", "addlicense_repo")

kustomize_repo = use_repo_rule("//bazel:kustomize_toolchain.bzl", "kustomize_repo")

helm_repo = use_repo_rule("//bazel:helm_toolchain.bzl", "helm_repo")

kubeconform_repo = use_repo_rule("//bazel:kubeconform_toolchain.bzl", "kubeconform_repo")

gitleaks_repo = use_repo_rule("//bazel:gitleaks_toolchain.bzl", "gitleaks_repo")

golangci_lint_repo = use_repo_rule("//bazel:golangci_lint_toolchain.bzl", "golangci_lint_repo")

addlicense_repo(name = "addlicense_toolchain")

kustomize_repo(name = "kustomize_toolchain")

helm_repo(name = "helm_toolchain")

kubeconform_repo(name = "kubeconform_toolchain")

gitleaks_repo(name = "gitleaks_toolchain")

golangci_lint_repo(name = "golangci_lint_toolchain")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.from_file(go_mod = "//:go.mod")
go_sdk.nogo(
    includes = ["@//:__subpackages__"],
    nogo = "//bazel/nogo:nogo",
)

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
go_deps.gazelle_default_attributes(
    directives = [
        "gazelle:proto disable",
    ],
)
go_deps.gazelle_override(
    build_file_generation = "clean",
    path = "github.com/google/cel-go",
)
use_repo(go_deps, "co_honnef_go_tools", "com_github_go_openapi_runtime", "com_github_go_openapi_strfmt", "com_github_gordonklaus_ineffassign", "com_github_kisielk_errcheck", "com_github_nunnatsa_ginkgolinter", "com_github_onsi_ginkgo_v2", "com_github_onsi_gomega", "com_github_prometheus_alertmanager", "io_k8s_apimachinery", "io_k8s_client_go", "io_k8s_sigs_controller_runtime")
