# Copyright 2026 Silence-Operator Maintainers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//bazel:addlicense.bzl", "license_check")
load("//bazel:gitleaks.bzl", "gitleaks_test")
load("//bazel:kubeconform.bzl", "kubeconform_test")
load("//bazel:kustomization.bzl", "kustomization")

package(default_package_metadata = ["//:package_metadata"])

kustomization(
    name = "install",
    srcs = glob(["*.yaml"]) + [
        "//config/crd:files",
        "//config/manager:files",
        "//config/rbac:files",
    ],
    out = "install.yaml",
)

kubeconform_test(
    name = "kubeconform",
    size = "small",
    srcs = [":install"],
)

gitleaks_test(
    name = "gitleaks",
    size = "small",
    src = ":install",
)

license_check(patterns = [])
