apiVersion: monitoring.coreos.com/v1alpha1
kind: Silence
metadata:
  labels:
    app.kubernetes.io/name: silence-operator
    app.kubernetes.io/managed-by: kustomize
  name: silence-sample
spec:
  # TODO(user): Add fields here
