{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: silence-operator-manager-role
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - silences
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - silences/finalizers
    verbs:
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - silences/status
    verbs:
      - get
      - patch
      - update
{{- end }}
