apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: silence-operator
  name: silence-operator-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app: silence-operator
