apiVersion: v1
kind: Service
metadata:
  labels:
    app: silence-operator
  name: silence-operator
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app: silence-operator
