apiVersion: v1
kind: Service
metadata:
  name: silence-operator-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "chart.selectorLabels" . | nindent 6 }}
